---
name: Static Analysis

on: [push]

jobs:
  Markdown_Lint_Check:
    name: Markdown Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run markdownlint
        run: |
          echo "Checking Markdown files"
          markdownlint '**/*.md'

  YAML_Lint_Check:
    name: YAML Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Install yamllint
        run: sudo apt install yamllint
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run yamllint
        run: |
          echo "Checking YAML files"
          yamllint -c .yamllint.yaml .github/**/**.yaml

  Python_Lint_Check:
    name: Python Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Install pylint
        run: |
          pip install pylint
          pip install -r requierements.txt
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run pylint
        run: |
          echo "Checking Python files with pylint"
          pylint --fail-under=9 **.py
